---
title: "Figure 4: Th17 cells during EAE"
output: html_notebook
---

```{r}
rm(list = ls())
dir_proj <- "/singerlab/linglin/Th17_single_cell_eae_ut/"

library(Seurat)
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(dplyr)
library(tidyr)
library(tibble)
library(openxlsx)
source(paste0(dir_proj, "1_code/utils.R"))

#### configuration ####
dir_out <- paste0(dir_proj, "3_output/Figure_4/")
if(!dir.exists(dir_out)) dir.create(dir_out, recursive = T)
```

Load data.
```{r}
prep_type_date <- "dominant_TCR_2020-03-24"
clustering_date <- "2020-04-16"
meta <- read.table(paste0(dir_proj, "2_pipeline/clustering/all_inter/", 
                          clustering_date, "/FILES/meta_data.csv"), 
                   header = T, row.names = 1, sep = ",")
reductions <- readRDS(paste0(dir_proj, "2_pipeline/clustering/all_inter/", clustering_date, "/FILES/reductions.rds"))
stopifnot(all(rownames(meta) == colnames(so_all)))
stopifnot(all(rownames(meta) == rownames(reductions$umap@cell.embeddings)))

so_all@meta.data <- meta
```

## Figure 4A: UMAP of all cells, color by tissue origin
```{r}
tissue_vec <- c("SPL", "MLN", "PP", "SI", "COL", "CNS", "DLN")
plt_df <- data.frame(
  tissue = factor(so_all$tissue, levels = tissue_vec),
  UMAP_1 = reductions$umap@cell.embeddings[,"UMAP_1"],
  UMAP_2 = reductions$umap@cell.embeddings[,"UMAP_2"]
)
p <- ggplot(plt_df, aes(x = UMAP_1, y = UMAP_2, color = tissue)) + 
  geom_point(size = 0.1) +
  scale_color_manual(values = tissue_colors(tissue_vec)) +
  labs(color = "Tissue") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_classic() +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12))
p_legend <- get_legend(p)
pdf(file = paste0(dir_out, "Fig4A.pdf"), width = 7, height = 7)
p + theme(legend.position = "none")
grid.arrange(p_legend)
dev.off()
```


## Figure 4B: UMAP of all cells, color by treatment (Naïve vs. EAE)
```{r}
plt_df <- data.frame(
  treatment = factor(so_all$treatment, levels = c("UT", "EAE"), labels = c("Naïve", "EAE")),
  UMAP_1 = reductions$umap@cell.embeddings[,"UMAP_1"],
  UMAP_2 = reductions$umap@cell.embeddings[,"UMAP_2"]
)

## shuffle the order of cells to avoid clutter by treatment
set.seed(1)
plt_df <- plt_df[sample(seq_along(plt_df[,1]), nrow(plt_df), replace = F),]

## set colors
col_treatment <- ggplot_default_color_descrete(2)
names(col_treatment) <- c("EAE", "Naïve")

p <- ggplot(plt_df, aes(x = UMAP_1, y = UMAP_2, color = treatment)) + 
  geom_point(size = 0.1) +
  scale_color_manual(values = col_treatment) +
  labs(color = "") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_classic() +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12))
p_legend <- get_legend(p)
pdf(file = paste0(dir_out, "Fig4B.pdf"), width = 7, height = 7)
p + theme(legend.position = "none")
grid.arrange(p_legend)
dev.off()
```


## Figure 4C: UMAP of all SPL cells, color by treatment (Naïve vs. EAE)
```{r}
clustering_date <- "2020-05-07"
meta_all_SPL <- read.table(paste0(dir_proj, "2_pipeline/clustering/all_intra/", clustering_date, "/FILES/SPL/meta_data.csv"), 
                           sep = ",", header = T, row.names = 1)
reductions_all_SPL <- readRDS(paste0(dir_proj, "2_pipeline/clustering/all_intra/", clustering_date, "/FILES/SPL/reductions.rds"))
stopifnot(all(rownames(meta_all_SPL) == rownames(reductions_all_SPL$umap@cell.embeddings)))

plt_df <- data.frame(
  treatment = factor(meta_all_SPL$treatment, levels = c("UT", "EAE"), labels = c("Naïve", "EAE")),
  UMAP_1 = reductions_all_SPL$umap@cell.embeddings[,"UMAP_1"],
  UMAP_2 = reductions_all_SPL$umap@cell.embeddings[,"UMAP_2"]
)

## shuffle the order of cells to avoid clutter by treatment
set.seed(1)
plt_df <- plt_df[sample(seq_along(plt_df[,1]), nrow(plt_df), replace = F),]

## set colors
col_treatment <- ggplot_default_color_descrete(2)
names(col_treatment) <- c("EAE", "Naïve")

p <- ggplot(plt_df, aes(x = UMAP_1, y = UMAP_2, color = treatment)) + 
  geom_point(size = 0.1) +
  scale_color_manual(values = col_treatment) +
  labs(color = "") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_classic() +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12))
p_legend <- get_legend(p)
pdf(file = paste0(dir_out, "Fig4C.pdf"), width = 7, height = 7)
p + theme(legend.position = "none")
grid.arrange(p_legend)
dev.off()
```


## Figure 4D: Volcano plot for EAE vs. Naïve in SPL
```{r}
library(ggrepel)
date_analysis <- "2020-12-13"
de_res <- readRDS(paste0(dir_proj, "2_pipeline/differential_expression/EAE_vs_UT_GFPall/", date_analysis, "/SPL_results.rds"))

genes_df <- read.xlsx(paste0(dir_proj, "3_output/old_figures/Figure4/Genes_spleen_volcanoplot.xlsx"), rowNames = T)
glist <- c(genes_df$Down, genes_df$Up)

thresh_log2fc <- log2(1.5)
thresh_fdr <- 0.05

de_up <- rownames(de_res$table)[de_res$table$logFC > thresh_log2fc & de_res$table$FDR < thresh_fdr]
de_down <- rownames(de_res$table)[de_res$table$logFC < -thresh_log2fc & de_res$table$FDR < thresh_fdr]
deg <- c(de_up, de_down)

plt_df <- de_res$table %>%
  rownames_to_column(var = "gene") %>%
  filter(!(grepl("Rps", gene) | grepl("Rpl", gene))) %>% 
  mutate(up_in = ifelse(logFC > thresh_log2fc & FDR < thresh_fdr, "EAE",
                        ifelse(logFC < -thresh_log2fc & FDR < thresh_fdr, "Naïve", "N.S.")) %>%
           factor(levels = c("Naïve", "EAE", "N.S."))) %>%
  mutate(label = ifelse((gene %in% glist & up_in != "N.S.") | abs(logFC) > 2, gene, NA))

## set colors
col_de <- c(ggplot_default_color_descrete(2), "black")
names(col_de) <- c("EAE", "Naïve", "N.S.")

p <- ggplot(plt_df, aes(x = logCPM, y = logFC, color = up_in)) +
  geom_point() +
  geom_label_repel(aes(label = label)) +
  scale_color_manual(values = col_de) +
  labs(x = "Average Log2 CPM", y = "Log2 Fold Change (EAE vs. Naïve)") +
  theme_bw() +
  theme(legend.position = "none")


pdf(file = paste0(dir_out, "Fig4D.pdf"), width = 5, height = 5)
p
dev.off()

```


## Figure 4E: Heatmap for TCR sharing across tissues
```{r}
library(pheatmap)

date_analysis <- "2020-12-10"
clone_size_ls <- readRDS(paste0(dir_proj, "2_pipeline/TCR/compare_tissue/size_table_EAE_", date_analysis, ".rds"))

total_size <- rowSums(clone_size_ls$pooled)
min_total_size <- 10

plt_mtx <- clone_size_ls$pooled[total_size > min_total_size,]
plt_mtx_scale <- 100 * apply(plt_mtx, 2, function(x){x/sum(x)})
plt_mtx_scale_cap <- pmin(plt_mtx_scale, quantile(plt_mtx_scale, 0.9))

p <- pheatmap(plt_mtx_scale_cap, 
              cluster_rows = TRUE, 
              cluster_cols = TRUE, 
              clustering_method = "ward.D2",
              show_rownames = F, 
              color = rev(col_corr_pos_skip(100)),
              fontsize = 8,
              fontsize_col = 11,
              silent = T)
which_col_names <- which(p$gtable$layout$name == "col_names")
p$gtable$grobs[[which_col_names]]$gp$col = tissue_colors(p$tree_col$labels[p$tree_col$order])
p$gtable$grobs[[which_col_names]]$rot = 45
p$gtable$grobs[[which_col_names]]$hjust = 1
p$gtable$grobs[[which_col_names]]$vjust = 1
p$gtable$grobs[[which_col_names]]$gp$fontsize = 13

pdf(file = paste0(dir_out, "Fig4E.pdf"), width = 4, height = 6)
grid.arrange(p$gtable)
dev.off()
```


## Figure 4F: Corrplot for TCR sharing across tissues (TRSS)
```{r}
date_analysis <- "2021-01-21"
bh_hc_ls <- readRDS(paste0(dir_proj, "2_pipeline/TCR/compare_tissue/bh_hclust_EAE_", date_analysis, ".rds"))
bh_dist_ls <- readRDS(paste0(dir_proj, "2_pipeline/TCR/compare_tissue/bh_similarity_EAE_", date_analysis, ".rds"))

library(corrplot)
library(dendextend)

pdf(file = paste0(dir_out, "Fig4F.pdf"), width = 7, height = 7)
layout(matrix(c(1, 1, 2, 2, 2, 2, 2, 2, 2, 2), nrow = 10, ncol = 1, byrow = TRUE))
## dendrogram
par(mar=c(0, 7, 2, 6.5))
dend <- as.dendrogram(bh_hc_ls$pooled)
dend %>% set("labels", "") %>% plot()
## corrplot
corrplot(bh_dist_ls$pooled,
         is.corr = F,
         type="upper", order="original", method = "circle",
         outline = T,
         col = rev(col_corr(200)),
         mar = c(0, 0, 0, 0),
         tl.col = tissue_colors(rownames(bh_dist_ls$pooled)),
         tl.pos = 'td', tl.cex = 2,
         diag = T, na.label = " ")
dev.off()
```

